[package]
name = "mascw/hammond-you-idiot-server"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "server"

[server-dependencies]
ProfileService = "firebird702/profileservice@1.1.0"
